# Generated by Django 5.2.6 on 2025-10-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('night_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product1',
        ),
    ]
